### PR TITLE
feat(query_rules): Add support for query rules

### PR DESCRIPTION
**Pull request by ElPicador**

### CODE REVIEW

**Comment by clement-leprovost** [comment]
My fault, as I forgot to state that explicitly: The naming should be coordinated with the other API clients, and we went for "rules" alone, not "query rules" for method naming. So this would be `saveRule` instead of `saveQueryRules`. Sorry for that... 😬

**Comment by ElPicador** [comment]
Fixed!

**Review by clement-leprovost — APPROVED** [review]
Thanks! LGTM 👍

**Comment by ElPicador** [comment]
@clement-leprovost PR updated, the tests are good now.

**Comment by clement-leprovost** [comment]
LGTM 👍

**Pull request merged**
