### PR TITLE
Add method partialUpdateObjectNoCreate

### PR DESCRIPTION
**Pull request by A21z**
partialUpdateObjectNoCreate is like partialUpdateObject but with parameter createIfNotExists=false

### CODE REVIEW

**Comment by Nagriar** [comment]
@A21z Thanks!

**Comment by A21z** [comment]
You're welcome! @Nagriar 
Would you mind releasing a 1.3.6 version with these commits?

**Comment by redox** [comment]
I've just released the 1.3.6 version; it will be propagated to Maven Central in the next few minutes.

**Comment by A21z** [comment]
Thanks!

**Pull request merged**
