### PR TITLE
Remove duplicates, fix javadoc

### PR DESCRIPTION
**Pull request by ElPicador**

### CODE REVIEW

**Comment by ElPicador** [comment]
I managed to run the tests locally (as it does not work with travis and PR), and it fails ...
So don't merge it yet

**Comment by vvo** [comment]
@ElPicador did you set the right env variables for the test to use (appid and apikey)?

**Comment by ElPicador** [comment]
In local yes, I'm in the process to fix them

**Comment by ElPicador** [comment]
Should be safe to review/merge

**Comment by ElPicador** [comment]
up ?

**Comment by redox** [comment]
:+1: @ElPicador

**Pull request merged**
